services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentplatform-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 