services:
  # Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agentplatform-sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
      MSSQL_PID: "${MSSQL_PID}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - agentplatform-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: ./AgentPlatform.API/Dockerfile
    container_name: agentplatform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - AgentRuntime__BaseUrl=${AgentRuntime__BaseUrl}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
      agent-core:
        condition: service_started
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - agentplatform-network

  # Agent Core (Python)
  agent-core:
    build:
      context: ./backend/AgentPlatform.Core
      dockerfile: Dockerfile
    container_name: agentplatform-agent-core
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - FLASK_ENV=${FLASK_ENV}
      - PORT=${PORT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/AgentPlatform.Core/uploads:/app/uploads
      - ./backend/AgentPlatform.Core/agents.json:/app/agents.json
    networks:
      - agentplatform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agentplatform-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      api:
        condition: service_started
    networks:
      - agentplatform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlserver_data:

networks:
  agentplatform-network:
    driver: bridge 
