version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agentplatform-sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - agentplatform-network

  api:
    build:
      context: .
      dockerfile: ./AgentPlatform.API/Dockerfile
    container_name: agentplatform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=agentplatform;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true
      - AgentRuntime__BaseUrl=http://adk-agent:8000
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    volumes:
      - ./uploads:/app/uploads
    networks:
      - agentplatform-network

  adk-agent:
    build:
      context: ./ADKAgentCore
      dockerfile: Dockerfile
    container_name: agentplatform-adk
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./ADKAgentCore/uploads:/app/uploads
    networks:
      - agentplatform-network

volumes:
  sqlserver_data:

networks:
  agentplatform-network:
    driver: bridge 