services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agentplatform-sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - agentplatform-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: ./AgentPlatform.API/Dockerfile
    container_name: agentplatform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=agentplatform;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true
      - AgentRuntime__BaseUrl=http://agent-core:8000
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
      agent-core:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
    networks:
      - agentplatform-network

  agent-core:
    build:
      context: ./AgentPlatform.Core
      dockerfile: Dockerfile
    container_name: agentplatform-agent-core
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - PORT=8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./AgentPlatform.Core/uploads:/app/uploads
      - ./AgentPlatform.Core/agents.json:/app/agents.json
    networks:
      - agentplatform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlserver_data:

networks:
  agentplatform-network:
    driver: bridge 